# Generated by Django 5.1.1 on 2024-09-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('senha', models.TextField(max_length=15)),
                ('cpf', models.IntegerField()),
                ('data', models.DateField()),
                ('telefone', models.TextField(max_length=15)),
            ],
        ),
    ]
